Initialize with components
ab-noori/bookstore pull request #1
Opened 2023-04-22 19:10 UTC by ab-noori

## Bookstore:  components initialization

  ###  🌟Features:

- [ ]  Three pages [`home`](https://github.com/ab-noori/math-magicians/blob/1d0553a4ac2152a53426f232bd73f7f10ff77f8b/src/components/Home.js), [`calculator`](https://github.com/ab-noori/math-magicians/blob/1d0553a4ac2152a53426f232bd73f7f10ff77f8b/src/components/Calculator.js), [`quote`](https://github.com/ab-noori/math-magicians/blob/1d0553a4ac2152a53426f232bd73f7f10ff77f8b/src/components/Quote.js) as separate components are added.
- [ ] All three pages are routed through [`App.js`](https://github.com/ab-noori/math-magicians/blob/1d0553a4ac2152a53426f232bd73f7f10ff77f8b/src/App.js) using React Router.
- [ ] The project is styled using React basic styling (CSS [`pre-processed Sass`](https://github.com/ab-noori/math-magicians/blob/1d0553a4ac2152a53426f232bd73f7f10ff77f8b/src/App.scss) files).
- [ ] Test files are added for [`calculate`](https://github.com/ab-noori/math-magicians/blob/792ecb52a639103b05c71ec296a6636908b1ec9a/src/tests/calculate.test.js) and [`operate`](https://github.com/ab-noori/math-magicians/blob/792ecb52a639103b05c71ec296a6636908b1ec9a/src/tests/operate.test.js) modules.
- [ ] [`Jest snapshots`](https://github.com/ab-noori/math-magicians/tree/tests/src/tests/__snapshots__) test is added for all components.
- [ ] [`Interactions`](https://github.com/ab-noori/math-magicians/tree/tests/src/tests/__interactions__) test is added for all components using React Testing Library.

### [ 🚀 Project Demo](#)

2023-04-22 19:26 UTC, 1GORDON reviewed
##
## Hi @ab-noori ✋

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and it won't affect the number of your weekly reviews.

- [ ] Kindly use the correct [readme template](https://github.com/microverseinc/readme-template) for your project.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 19:38 UTC, ab-noori commented
Hi @1GORDON,

I have just updated the readme file,
please recheck it!
I am sorry to say this, but I am facing a tight deadline.

2023-04-22 23:00 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @ab-noori  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 

- No linter errors :+1: 
- Good use of Gitflow :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 23:00 UTC, GedeonTS commented on src/App.js
> +        </Router>
- Kindly make sure your Routes are working well, for this I suggest  putting everything inside Router instead of only the Routes container.

```
  <Router>
      <header>
        <Navigation />
      </header>

      <main>

          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/boostore/categories" element={<Categories />} />
          </Routes>
 
      </main>

      <footer>
        <p className="copyright">&copy; 2023 Bookstore CMS | Developed by Abdulali Noori</p>
      </footer>
       </Router>
```

- In addition to that, it's necessary to make your home route path="/" to make sure it doesn't show a blank page when it start :recycle:

2023-04-24 08:35 UTC, Nemwel-Boniface reviewed
## Hello @ab-noori 

### This is a manual review

# :heavy_check_mark: Approved :heavy_check_mark: 

Good job making all the requested changes :rocket: 

Cheers and Happy coding!

2023-04-26 17:30 UTC, merged